### ISSUE TITLE
No Audio On Lenovo Miix 320 with Elementary OS-Loki

### ISSUE THREAD

**Issue by nisargmehta1** [khedoros/khedgb#5]
I have the same sound card in my netbooks as mentioned in this post: https://elementaryos.stackexchange.com/questions/14923/asus-e200h-intel-hdmi-for-internal-speakers-fix

There is no audio coming from the netbook speakers and the headphone jack. how can I fix it. Please help.

**Comment by khedoros** [comment]
There is no audio in the emulator because the simulation for that part of the hardware isn't done, and I already have an issue open tracking that: https://github.com/khedoros/khedgb/issues/1

**Comment by nisargmehta1** [comment]
I am not talking about no audio issue on emulator. I am facing this issue when Elementary OS is installed on my Lenovo Netbook as primary and only OS! Please help.
